### ISSUE TITLE
Error in the documentation (slf4j.binding)

### ISSUE THREAD

**Issue by jeromevdl** [qos-ch/slf4j#356]
In the documentation it is written:

> SINCE 2.0.8 You can specify the provider class explicitly via the "slf4j.binding" system property. This bypasses the service loader mechanism for finding providers and may shorten SLF4J initialization.

But looking at the code ([here](https://github.com/qos-ch/slf4j/blob/7c164fab8d54f823dd55c01a5a839c153f578297/slf4j-api/src/main/java/org/slf4j/LoggerFactory.java#L90)), it is not `slf4j.binding` but **`slf4j.provider`**.

Can you update the documentation ?

**Comment by ceki** [comment]
Thank you for reporting this problem. The issue has been fixed.
