### ISSUE TITLE
Version 2.0.14 on Maven Central, but not tagged

### ISSUE THREAD

**Issue by Stephan202** [qos-ch/slf4j#420]
Hey @ceki! Renovate opened an [upgrade PR](https://github.com/PicnicSupermarket/error-prone-support/pull/1272) in our repository because version 2.0.14 became available on [Maven Central](https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.14/), but this repository doesn't have an associated [tag](https://github.com/qos-ch/slf4j/releases/tag/v_2.0.14) yet. (I assume that a new [news](https://www.slf4j.org/news.html) entry is simply still on the TODO list, but I opened this issue because pushing the tag is presumably something that's usually done as part of the release processes.)

**Comment by Stephan202** [comment]
Ah, the [news](https://www.slf4j.org/news.html) message does state `v_2.0.14`, so it might be nice to align that :)

**Comment by ceki** [comment]
@Stephan202  Added tag v_2.0.14 without removing v2.0.14.
