### ISSUE TITLE
Unexpected new log `SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]`

### ISSUE THREAD

**Issue by metametadata** [qos-ch/slf4j#422]
After bumping `org.slf4j/slf4j-api` from `2.0.13` to `2.0.14` I see an unexpected message printed in my projects:

> SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]

<hr/>

* I'd consider this a useless information for the majority of users.
* It can be turned off via `System.setProperty("slf4j.internal.verbosity", "WARN")`, but I maintain many projects and use Clojure, so it's an inconvenient workaround.
* As was pointed out in [https://stackoverflow.com/questions/78063648](https://stackoverflow.com/questions/78063648/how-to-stop-slf4j-printing-a-pointless-information-message-at-startup#comment137620907_78063825):

   > Interestingly, it was changed in [commit 8f8691065dc432f1d47b1307610e447c37d52ef8 at Dec 18, 2023](https://github.com/qos-ch/slf4j/commit/8f8691065dc432f1d47b1307610e447c37d52ef8#diff-204f23f1c787a5f1f6162f79eae7d8694d723ef7788e23b79ed270a15c677b00). Not sure why the isAmbiguousProviderList() check was removed...

**Comment by ceki** [comment]
@metametadata I understand that the message may be considered useless. However, in many cases when logging does not work as expected, the information about the provider in use goes a long way in diagnosing logging issues.

As for the removal of `isAmbiguousProviderList` check, the check for multiple Provider ambiguity is reported earlier if relevant, but a successful connection with a provider is now reported every time regardless of provider ambiguity.

**Comment by metametadata** [comment]
> As for the removal of isAmbiguousProviderList check, the check for multiple Provider ambiguity is reported earlier if relevant, but a successful connection with a provider is now reported every time regardless of provider ambiguity.

Right, the point was that the change is unjustified or even looks unintentional as the commit message is `migrate to Java 11` 🤷 But it's clear now, thanks!

Maybe as an alternative, this info could be printed at some kind of DEBUG level (or something like that)? So that by default users don't see it, but will see this message on bumping into problems and enabling the "debug mode" of slf4j.

**Comment by ceki** [comment]
@metametadata The commit you mention is on the 2.1 branch. The message for the commit 42810107b0ec38ec568e0501f4ab20e01a153eef on the 2.0/main branch is much clearer. However, I get your point.

Thank you for your suggestion. I have to let the question mature somewhat more and may end up adopting something similar.

**Comment by jonesbusy** [comment]
Also started to appear after upgrade https://github.com/jenkinsci/plugin-modernizer-tool/pull/168

```
SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]
```

I don't expect a patch upgrade starting to print this line on a CLI application when it start. It's kind of confusing.

For us `System.setProperty("slf4j.internal.verbosity", "WARN")` did the trick

**Comment by lprimak** [comment]
What makes this a critical issue is that this message is printed to `stderr`, which causes alerts from all sorts of monitoring tools.

At the very least, it should go to `stdout` or, better yet, none at all, i.e. DEBUG level as suggested earleier

**Comment by ceki** [comment]
Fixed as suggested by @metametadata. See [version 2.0.16 release notes](https://www.slf4j.org/news.html#2.0.16).

**Comment by metametadata** [comment]
Thank you!

**Comment by bschuhmann** [comment]
@ceki, in case `slf4j.provider` is set, there's another log message I'd consider _unexpected_:
```
SLF4J(I): Attempting to load provider "org.apache.logging.slf4j.SLF4JServiceProvider" specified via "slf4j.provider" system property
```
Is there a reason this should stay on `INFO` level? I'm setting `slf4j.provider` explicitly, so _expect_ it is used - and only if it isn't I can change the log level to `DEBUG` and verify `slf4j.provider` has been picked up or not.

**Comment by wohler** [comment]
This message has seemed to rear its ugly head again in 2.1.0-alpha1.
