### ISSUE TITLE
Javadoc of org.slf4j.helpers.Slf4jEnvUtil.slf4jVersion() refers to logback

### ISSUE THREAD

**Issue by hankem** [qos-ch/slf4j#423]
[The javadoc of `org.slf4j.helpers.Slf4jEnvUtil.slf4jVersion()`](https://javadoc.io/static/org.slf4j/slf4j-api/2.0.14/org/slf4j/helpers/Slf4jEnvUtil.html#slf4jVersion()), introduced with version 2.0.14, refers to `logback`
(just as [the javadoc of `ch.qos.logback.core.util.EnvUtil.logbackVersion()`](https://github.com/qos-ch/logback/blob/v_1.3.0/logback-core/src/main/java/ch/qos/logback/core/util/EnvUtil.java) does 😉),
but it should probably rather be `slf4j` here.

**Comment by ceki** [comment]
@hankem Thank you
