### ISSUE TITLE
slf4j-jdk-platform-logging always logging Level.ALL messages regardless of logger level

### ISSUE THREAD

**Issue by peterhalicky** [qos-ch/slf4j#430]
So, sun.security.ssl.SSLLogger logs its `finest` events with `Level.ALL`. While that on its own is a bug (and I reported it), I'd say slf4j-jdk-platform-logging is still handling it incorrectly. It gets written out as `TRACE` level, regardless of level setting of the logger.

I'm all for treating the `Level.ALL` as `TRACE`, but it should also be filtered as such. I suppose in `SLF4JPlatformLogger.log(...)` method instead of current:

```java
        if (jplLevel == Level.ALL) {
            performLog(org.slf4j.event.Level.TRACE, bundle, msg, thrown, params);
            return;
        }
```

it should be:

```java
        if (jplLevel == Level.ALL) {
            if (slf4jLogger.isEnabledForLevel(org.slf4j.event.Level.TRACE)) {
                performLog(org.slf4j.event.Level.TRACE, bundle, msg, thrown, params);
            }
            return;
        }
```

I will gladly submit a PR if this looks okay to the relevant people here.

**Comment by ceki** [comment]
@peterhalicky  Fixed in commit f7b34c2e60ebf242003675490dcbbeae52f. Let me know what you think.

**Comment by peterhalicky** [comment]
@ceki I'm not sure if I agree with mapping the Level.OFF level to Level.ERROR -- which in most typical configuration will be written to the log; I'd guess if someone logs with Level.OFF, he probably means to never actually write it in the log -- so if not dropping the message completely I'd probably instead map it to Level.TRACE (kinda same as Level.ALL, which is counterintuitive -- but it's counterintuitive to actually use those levels anyway).

**Comment by ceki** [comment]
Indeed, Level.OFF and Level.ALL are a quite counter intuitive when used as logging levels.

However, no one is supposed to use Level.OFF and Level.ALL **for logging**. They are intended for filtering and are vestigial from log4j 1.x where it was possible to subclass Level to create custom levels. In logback and log4j2 the Level class is final. Thus, Level.OFF and Level.ALL make little sense.
 
Also, Level.OFF has the highest priority (not the lowest). Level.ALL has the lowest priority (not the highest).

**Comment by peterhalicky** [comment]
What I'm worried about is that when someone non-sensically uses Level.OFF for logging and we map it to Level.ERROR, it will be difficult to get rid of those messages.

**Comment by ceki** [comment]
On the contrary, in that case, you would assign the level of the **logger** to Level.OFF and the message would not be printed (which is the desired outcome).

**Comment by peterhalicky** [comment]
Well, but if the logger is actually logging something useful at Level.INFO, WARN or ERROR, we'd miss that.

**Comment by ceki** [comment]
With only the logger-level filter, it is impossible for a logger to simultaneously suppress messages of Level.ERROR and allow messages of Level.WARN. When Level.OFF is mapped to SLF4J-Level.ERROR, you can at least suppress the message if you really wanted to.

**Comment by agentgt** [comment]
@ceki I agree with @peterhalicky assessment and I talked about this in #407 . 

> However, no one is supposed to use Level.OFF and Level.ALL **for logging**. They are intended for filtering and are vestigial from log4j 1.x where it was possible to subclass Level to create custom levels. In logback and log4j2 the Level class is final. Thus, Level.ALL makes little sense while Level.OFF can be used to filter out all logging.

`Level.OFF` and `Level.ALL` are the JDK logging levels and not log4j 1.x. I know JUL was inspired by log4j but it has its own API with documentation. As I showed in #407 (which predates this bug) you can easily create `LogRecord` with those levels and it is very easy to see how one would accidentally pass `Level.OFF` programmatically.

The things is the slf4j-jdk-platform-logging is to be implementing the `System.Logger` facade and not SLF4J, logback or log4j2 and `System.Logger` clearly has the enum `Level.OFF`. When implementing a facade you should follow the facades interpretations ideally.

But the most damning thing is the `System.Logger` implementations in [Log4j2](https://github.com/apache/logging-log4j2/blob/04c93c1d33f7d0fc46fe4f390ea1968e8d93c485/log4j-jpl/src/main/java/org/apache/logging/log4j/jpl/Log4jSystemLogger.java#L112), JUL, and my own library RainbowGum interpret `System.Level.OFF` as a NOOP. 

EDIT let me give you or others I think a common scenario.

Developer writes open source library.

Does something like

```java
boolean isError = ...;
String output = ...;
System.Logger.Level level = isError ? System.Logger.ERROR : System.Logger.OFF;
logger.log(level, output);
```

Developer uses Apache Log4j2, or JUL, or Rainbow Gum for unit testing and sees no error or just you know interprets OFF like everyone else does and sees no problem. 

Anyone using slf4j-jdk-platform-logging is going to have a bad day.

**Comment by ceki** [comment]
@agentgt  Hello Adam,

Let me get this straight. You expect the following code to **not** log anything. Is that what you are saying?

```
System.Logger logger = System.getLogger("com.foo.Main");
logger.log(System.Logger.Level.OFF, "Hello world");

```

**Comment by agentgt** [comment]
> Let me get this straight. You expect the following code to not log anything. Is that what you are saying?

Correct or at least TRACE.

Per the javadoc the severity integers of ALL and OFF mean nothing. They just picked those numbers and they picked the lowest for ALL and maximum for OFF but they very easily could have done the opposite.

That is you picked ALL to be TRACE and OFF to be ERROR because of the severity integer correct?

I would say if you are going to have OFF be ERROR, ALL should be ERROR as well or here is a more sophisticated solution: You create Markers since you know SLF4J has that and System.Logger does not so no collision and the Javadoc literally say those levels are "markers":

```java
var OFF = MarkerFactory.getMarker("System.Level.OFF");
var ALL = MarkerFactory.getMarker("System.Level.ALL");
```

Then presumable someone downstream can filter out the messages or actually reapply them to a different level.

But the simplest solution is to have OFF do nothing and I doubt anyone would complain.

**Comment by agentgt** [comment]
Sorry @ceki I missed your recent changes. Yes I like your new changes of reporting both ALL and OFF! I think that is the best solution.
