### ISSUE TITLE
org/slf4j/LoggerFactory error when using pdfcompare ivy.xml dependencies 

### ISSUE THREAD

**Issue by heenavasdani1** [qos-ch/slf4j#441]
Hi @laurio , @geofflane , @abstractj , @ceefour , @sullis

I'm experiencing an issue when using the pdfcompare library in my project. I have an ivy.xml file that contains the following dependencies:

`<dependency org="apache" name="commons-cli" rev="1.2" conf="release,dev->*" /> <dependency org="selenium" name="selenium" rev="3.7.0" conf="release,dev->*" /> <dependency org="testng" name="testng" rev="6.14" conf="release,dev->*" /> <dependency org="apache" name="log4j" rev="1.2.16" conf="release,dev->*" /> <dependency org="apache" name="freemarker" rev="2.3.28" conf="release,dev->*" /> <dependency org="jcommander" name="jcommander" rev="1.48" conf="release,dev->*" /> <dependency org="relevantcodes" name="extentreports" rev="2.41.2" conf="release,dev->*" /> <dependency org="rest-assured" name="restassured" rev="4.3.0" conf="release,dev->*" /> <dependency org="BeyondCompare" name="BCompare" rev="3.0.15.9758" conf="release,dev->*" /> <dependency org="poweradmin" name="psexec" rev="2.4.5" conf="release,dev->*" /> <dependency org="sqlite" name="sqlite-jdbc" rev="3.23.1" conf="release,dev->*" /> <dependency org="jna" name="jna" rev="5.8.0" conf="release,dev->*" /> <dependency org="eclipse" name="jaxb" rev="2.3.2" conf="release,dev->*" /> <dependency org="apache" name="pdfbox" rev="2.0.23" conf="release,dev->*" /> <dependency org="de.redsix" name="pdfcompare" rev="1.2.3" conf="release,dev->*" /> <dependency org="org.slf4j" name="slf4j-api" rev="2.0.16" conf="release,dev->*" /> <dependency org="ch.qos.logback" name="logback-classic" rev="1.5.12" conf="release,dev->*"/>`

When I use the pdfcompare library in my Java tests, I'm getting the following error:

org/slf4j/LoggerFactory
I've tried the following to resolve the issue:

Removing the log4j dependency
Excluding the slf4j-api artifact from the pdfcompare dependency
Cleaning and rebuilding the project

However, the issue persists. I suspect there might be a conflict between the SLF4J versions or implementations being used by the different dependencies.
Could you please provide any guidance on how to resolve this issue? I'm happy to provide more information or diagnostics if needed.
Thank you for your assistance!

**Comment by ceki** [comment]
Hi @heenavasdani1  

The error description looks incomplete.

> When I use the pdfcompare library in my Java tests, I'm getting the following error:
> 
> org/slf4j/LoggerFactory

**Comment by heenavasdani1** [comment]
@ceki , Actually this error description is complete, I am getting only this error message when I am executing the below line of code-
`boolean isEqual = new PdfComparator(masterFilePath, testFilePath).compare().writeTo("result.pdf");`

For PdfComparator, I am using following line to import pdfCompare library(https://mvnrepository.com/artifact/de.redsix/pdfcompare)
`import de.redsix.pdfcompare.PdfComparator;`

PdfCompare's classes calling org.slf4j.Logger internally so it is not able to find slf4j. Please help me to resolve it, as I tried many things but nothing worked.
Thanks!
